Fix service dependencies in client class
At least in PE 2.5.1, the '~>' method was failing with a mysterious
error: undefined method `<<' for {}:Hash on node snarf.ucsd.edu

Switched to explicit subscribe metaparam